### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by steve-downey** [emacs-exordium/exordium#146]
We should state a license for the collective work.

Most of the work is based on orchestration of other elisp packages, but Exordium should have its own license, as it is now its own thing. The combination of `taps` with the before and after protocol, together with the reliable configurable base is novel. 

I have a preference for an OSI approved license

**Comment by steve-downey** [comment]
I don't have a strong preference here, other than continuing to make this available to anyone who is interested in using it. I have a weak preference for Apache 2.

**Comment by pkryger** [comment]
I’m completely noob when it comes to licensing. I guess I will agree to anything that os fairly permissive.

**Comment by steve-downey** [comment]
It's generally assumed that elisp code that makes significant use of emacs facilities should be licensed with a GPL compatible license. This is not a particularly heavy burden, particularly for code we're already publishing openly. 

The sensible set of choices is probably Apache 2, GPLv3, or 3-clause BSD. Others are roughly equivalent, or specialized for particular use cases.

**Comment by pkryger** [comment]
I think I was trying to show my inclination towards some permissive license vs. copyleft one, i.e. https://en.wikipedia.org/wiki/Permissive_software_license. The reason being that I used to work for a company that didn’t like GPL licenses and, had I known about exordium back then, using it would have required jumping through a few extra hoops. 

I’d vote for BSD or Apache (or if I can suggest a MIT). But will agree to a copyleft one.

**Comment by steve-downey** [comment]
MIT, a.k.a Expat to distinguish from some of the others MIT uses, would be fine. I agree about preferring permissive licences. And sometime in the last decade it apparently became a lot more popular. Showing my BSD roots, I suppose. 

@philippe-grenet @jll63 Any opinions?

**Comment by philippe-grenet** [comment]
The current license is MIT. That’s the one I choose when I created my original repo. I don’t have a strong opinion about any particular license for Exordium.

**Comment by steve-downey** [comment]
I'm entirely happy with MIT. What I missed is that it's in [COPYING](COPYING) rather than LICENCE.txt or md 
🤦‍♂️
