### ISSUE TITLE
[question] how to turn off key-binding suggestion?

### ISSUE THREAD

**Issue by jbongseo** [emacs-exordium/exordium#215]
After pressing prefix keys like `C-x` or `C-h` and stay still for seconds, then auto-complete(?) list of key-bindings are displayed on the bottom command line buffer (?) like below:

![image](https://github.com/emacs-exordium/exordium/assets/113876199/0e15b8e6-1614-44bf-aa18-986f4a4a7cb5)

But in my machine, it tooks 2~3 secs to show the list and it freezes emacs meanwhile.

a) How can I disable this suggestion feature?
b) Or how can I feature out which operation is freezing emacs?

Thanks in adavance!

**Comment by philippe-grenet** [comment]
Hello. I believe that this behavior comes from [which key](https://github.com/justbur/emacs-which-key), which was introduced with PR #168 . You can disable it by setting `exordium-help-extensions` to nil in your before-init.el file. Let me or @pkryger know if you have questions about it.

**Comment by jbongseo** [comment]
@philippe-grenet  Thanks a lot for fast reply! I adjusted which key setting using its document: https://github.com/justbur/emacs-which-key#manual-activation
