### ISSUE TITLE
Network-free startup option

### ISSUE THREAD

**Issue by philippe-grenet** [emacs-exordium/exordium#229]
I'd like to add an option in Exordium to make it not make any network connection when it starts. Obviously this isn't what you want for a fresh install, it needs to load a bunch of packages from Elpa the first time. But afterwards, it should be possible to start Emacs without calling Elpa. This matters when you are in a corporate environment where the VPN can be fuzzy with external sites, or when Elpa is down. It also make Emacs take even more time to start.

I think having making `(package-refresh-contents)` controlled by a new preference would be sufficient. Perhaps there is a more elegant solution?

**Comment by steve-downey** [comment]
I'd appreciate it, too. I occasionally have to, or want to, work disconnected, and not being able to restart emacs is occasionally a real problem.

**Comment by philippe-grenet** [comment]
@pkryger agree too? What's the right way to do it?

**Comment by pkryger** [comment]
I had very similar thoughts today. I guess prompted by the recent issue I stumbled upon, where too many calls from a single workflow to MELPA were causing it to crash. A bit more here https://github.com/emacs-exordium/exordium/commit/ab6109af5fd92e7e7f0325b15fa1fdcb87ce17b8. 

My thoughts were wandering around a concept where we'll keep some state (in a `emacs-custom.el`?) as when was last call to `package-refreshc-contents` made, and just don't do it if it has been made already? Perhaps with an extension to allow user to decide how long between automatic refreshes?

Alternatively, if we only want to allow Exordium do the first refresh to allow installing packages on a first start, then maybe there's a way to sense if package archive contents has been pulled in (I know that Emacs keeps some stuff in `package-user-dir`)?

However there are a few bonus points... that is `use-package` calls `package-refresh-contents` (when it cannot resolve some package). Perhaps that's a good thing to leave as is to support a scenario when Exordium has been upgraded and new packages were added that were not present in archive contents?

On the other hand if package contents were not refreshed, and new packages were added (i.e., after Exordium upgrade), then package metadata may be stale and refer to non-existing packages which will cause Exordium to fail to install it (MELPA rebuilds a few times a day).

Sorry for not having a more concise and determined approach, but I still try to wrap around all the possible use cases in my head. Appreciate your thoughts comments.

Last but not least: on corporate network I used to `node-proxy` with dynamically switched between appropriate proxy for VPN and direct connection when not needed. Emacs and `brew` worked as a charm. For example `brew` could install externally hosted dependencies while installing internally hosted packages, and Emacs was able to hit internal Jenkins and GitHub and MELPA at the same time. AFAIR I had some `brew` taps on internal GithHub with this configuration. And a special tap for Emacs on a corporate laptop to connect to right proxy.

**Comment by steve-downey** [comment]
One possibility might be setting an option on the command line to override the package refresh and updates? Something like https://www.reddit.com/r/emacs/comments/12yjtlv/custom_command_line_argument/  using https://www.gnu.org/software/emacs/manual/html_node/elisp/Command_002dLine-Arguments.html

**Comment by pkryger** [comment]
> One possibility might be setting an option on the command line to override the package refresh and updates? [...]

That's a great idea. I've been thinking about an automatic one but we can merge these two together. And perhaps add an option to inhibit refresh as well?

```emacs-lisp
(package-initialize)
(let ((last-exordium-commit (string-to-number
                             (let ((default-directory user-emacs-directory))
                               (shell-command-to-string
                                "git log -1 --format=%ct | tr -d '\n'"))))
      (last-archive-contents
       (apply #'max
              (or
               (mapcar (lambda (archive)
                         (let ((contents-file (file-name-concat
                                               package-user-dir
                                               "archives"
                                               (car archive)
                                               "archive-contents")))
                           (if (file-exists-p contents-file)
                               (time-convert (file-attribute-modification-time
                                              (file-attributes contents-file))
                                             'integer)
                             0)))
                       package-archives)
               (list 0))))
  (when (or
         ;; User has asked to refresh contents
         ((member "--exordium-package-refresh-contents" command-line-args))
         ;; No archive contents, likely a first Exordium start refresh package
         ;; contents to allow for packages installation
         (null package-archive-contents)
         ;; The newest archive contents is older than last Exordium commit:
         ;; refresh package contents to allow installation of possible new
         ;; packages
         (< last-archive-contents last-exordium-commit))
    (package-refresh-contents)))
```

**Comment by philippe-grenet** [comment]
That would work. PR?
